// Generated by Wrangler on Sun Jul 14 2024 17:54:53 GMT+0700 (เวลาอินโดจีน)
// by running `wrangler types`

interface Env {
	ENVIRONMENT: string;
	SESSION_SECRET: string;
	LINE_SECRET: string;
	LINE_OAUTH_CLIENT_ID: string;
	LINE_OAUTH_CLIENT_SECRET: string;
	CORS_ALLOW_ORIGIN: string;
	TICKET: DurableObjectNamespace;
	DB: D1Database;
}
