// Generated by Wrangler on Thu Jul 25 2024 08:35:45 GMT+0700 (เวลาอินโดจีน)
// by running `wrangler types`

interface Env {
	ENVIRONMENT: string;
	SESSION_SECRET: string;
	HMAC_SECRET: string;
	LINE_SECRET: string;
	LINE_OAUTH_CLIENT_ID: string;
	LINE_OAUTH_CLIENT_SECRET: string;
	CORS_ALLOW_ORIGIN: string;
	TURNSTILE_SECRET: string;
	TICKET: DurableObjectNamespace;
	DB: D1Database;
}
